version: '3.4'

services:

  friends-api:
    image: friends-api:latest
    depends_on:
      - user-service
      - group-service
    environment:
      PORT: 8000
      USER_SERVICE_URL: http://user-service:8000/
      GROUP_SERVICE_URL: http://group-service:8000/
    ports:
      - 8000:8000


  user-service:
    image: friends-user-service:latest
    depends_on:
      - outgoing-proxy-service
    environment:
      PORT: 8000
      KARTOFFEL_URL: http://outgoing-proxy-service:8000/kartoffel
    ports:
      - 8001:8000

  group-service:
    image: friends-group-service
    depends_on:
      - mongo
    environment:
      PORT: 8000
      MONGO_URI: mongodb://mongo:27017/devDB
      MONGO_FEATURE_COLLECTION_NAME: groups
      USER_HEADER: X-User-ID
    ports:
      - 8002:8000

  mongo:
    image: "mongo:4.0.9"
    ports:
      - "27017:27017"
    volumes:
      - "./data/db:/data/db"

  redis:
    image: redis
    ports:
      - 6379:6379

  outgoing-proxy-service:
    image: spike-proxy-service-master
    environment:
      MODE: outgoing
      PORT: 8000
      SPIKE_REDIS_HOST: redis://redis
      SPIKE_CLIENT_ID: hvOItpV~jv0ZiIqEAxLrYx8sxvDHmPfNiw9wtOSz
      SPIKE_CLIENT_SECRET: e2ar_pCJc27RdT4dFw~6ONYJ~5gVgsWfh9cjuUJ0YyVL0simY3VwehAYwe0qPB_uUIjRXFKzHJUqW7A_KM1DBpPYtQQ183JcdLFr
      SPIKE_URL: https://51.144.178.121:1337/oauth2/token
      TOKEN_GRANT_TYPE: client_credentials
      SPIKE_USER_SERVICE_REDIS_KEY_NAME: kartoffel
      SPIKE_PUBLIC_KEY_FULL_PATH: ./certificate/publicKey.pem
      USE_REDIS: 'true'
      OUTGOING_SERVICES: ##_OUTGOING_SERVICES_##
    ports:
      - 8003:8000

  incoming-spike-proxy:
    image: spike-proxy-service-master
    environment: 
      MODE: incoming
      PORT: 8000
      SPIKE_PUBLIC_KEY_FULL_PATH: ./certificate/publicKey.pem
      INCOMING_SERVICES: ##_INCOMING_SERVICES_##
    ports:
      - 8004:8000